
export const MOLECULES = [
  // 以下為原始資料保留項目
  { n: "水", f: { H: 2, O: 1 }, effect: "無法使用", acidity: "" },
  { n: "鹽酸", f: { H: 1, Cl: 1 }, effect: "腐蝕", acidity: "強酸" },
  { n: "硫酸", f: { H: 2, S: 1, O: 4 }, effect: "腐蝕", acidity: "強酸" },
  { n: "硝酸", f: { H: 1, N: 1, O: 3 }, effect: "腐蝕", acidity: "強酸" },
  { n: "氫氧化鈉", f: { Na: 1, O: 1, H: 1 }, effect: "腐蝕", acidity: "強鹼" },
  { n: "光氣", f: { C: 1, O: 1, Cl: 2 }, effect: "中毒", acidity: "" },
  { n: "氯仿", f: { C: 1, H: 1, Cl: 3 }, effect: "中毒", acidity: "" },
  { n: "甲烷", f: { C: 1, H: 4 }, effect: "燃燒", acidity: "" },
  { n: "乙炔", f: { C: 2, H: 2 }, effect: "燃燒", acidity: "" },
  { n: "乙烯", f: { C: 2, H: 4 }, effect: "燃燒", acidity: "" },

  // 以下為鹽類資料合併（已對照、未重複）
  { n: "氟化鈉", f: { Na: 1, F: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "溴化鈉", f: { Na: 1, Br: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "碘化鈉", f: { Na: 1, I: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "硫化鈉", f: { Na: 2, S: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氧化鈉", f: { Na: 2, O: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氮化鈉", f: { Na: 3, N: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "磷化鈉", f: { Na: 3, P: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氯化鋰", f: { Li: 1, Cl: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氟化鋰", f: { Li: 1, F: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "溴化鋰", f: { Li: 1, Br: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "硫化鋰", f: { Li: 2, S: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氧化鋰", f: { Li: 2, O: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氮化鋰", f: { Li: 3, N: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "磷化鋰", f: { Li: 3, P: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氯化鉀", f: { K: 1, Cl: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氟化鉀", f: { K: 1, F: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "溴化鉀", f: { K: 1, Br: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "碘化鉀", f: { K: 1, I: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "硫化鉀", f: { K: 2, S: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氧化鉀", f: { K: 2, O: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氮化鉀", f: { K: 3, N: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "磷化鉀", f: { K: 3, P: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氯化鎂", f: { Mg: 1, Cl: 2 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氟化鎂", f: { Mg: 1, F: 2 }, effect: "無法使用", acidity: "鹽類" },
  { n: "溴化鎂", f: { Mg: 1, Br: 2 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氧化鎂", f: { Mg: 1, O: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "硫化鎂", f: { Mg: 1, S: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氯化鈹", f: { Be: 1, Cl: 2 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氟化鈹", f: { Be: 1, F: 2 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氧化鈹", f: { Be: 1, O: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "硫化鈹", f: { Be: 1, S: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氯化鋁", f: { Al: 1, Cl: 3 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氟化鋁", f: { Al: 1, F: 3 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氧化鋁", f: { Al: 2, O: 3 }, effect: "無法使用", acidity: "鹽類" },
  { n: "硫化鋁", f: { Al: 2, S: 3 }, effect: "無法使用", acidity: "鹽類" },
  { n: "氮化鋁", f: { Al: 1, N: 1 }, effect: "無法使用", acidity: "鹽類" },
  { n: "磷化鋁", f: { Al: 1, P: 1 }, effect: "無法使用", acidity: "鹽類" },

  { n: "氫氧化鋰", f: { Li: 1, O: 1, H: 1 }, effect: "腐蝕", acidity: "強鹼" },
  { n: "氫氧化鉀", f: { K: 1, O: 1, H: 1 }, effect: "腐蝕", acidity: "強鹼" },
  { n: "氫氧化鈣", f: { Ca: 1, O: 2, H: 2 }, effect: "腐蝕", acidity: "" },
  { n: "氫氧化鎂", f: { Mg: 1, O: 2, H: 2 }, effect: "無法使用", acidity: "" },
  { n: "氫氧化鋁", f: { Al: 1, O: 3, H: 3 }, effect: "無法使用", acidity: "" }
];
